steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.review
      - --tag
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}

serviceAccount: projects/$PROJECT_ID/serviceAccounts/podcast-review-build@YOUR_GCP_PROJECT_ID.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
